[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
forestroad_curator_vault = "3ZPRvNDUDRZuZ8Hug873JtSDJueA8D7PEVE21uLLAvwh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p forestroad-curator-vault"

[hooks]
