// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";
import {IAccessControl} from "@openzeppelin/contracts/access/IAccessControl.sol";

import {Deploy} from "../../script/Deploy.s.sol";
import {HandoverOps} from "../../script/Handover.s.sol";
import {Validate} from "../../script/Validate.s.sol";
import {PrivilegeAudit} from "../../script/PrivilegeAudit.sol";
import {Roles} from "../../src/libraries/Roles.sol";

/// @title P-31 discriminator — the proposal guardian is a named ceremony principal that no
///        blocking privilege scan covers.
///
/// @dev WRITTEN BY THE AUDIT STREAM, NOT BY THE STREAM THAT WILL FIX IT. Same separation as the
///      P-23 and cause-E/F discriminators. **Do not edit this file to match a fix** — if the fix
///      takes a different shape, say so and the test will be re-pointed deliberately.
///
///      THE FINDING. The four-input merge promoted `proposalGuardian` to a first-class ceremony
///      principal: `Deploy.Ctx` (Deploy.s.sol:145), the env read (263), `FRGovernor.initialize`,
///      the manifest, `Handover`'s manifest read (785-786), `Validate._load` (180-181) and
///      `MainnetDeploymentReceipt.principalSetHash`. `Validate` even PRINTS it —
///      `RETAINED PRIVILEGE proposalGuardian -> ...` at Validate.s.sol:1059-1064.
///
///      But no BLOCKING assertion covers it:
///        - `Validate._assertNamedPrincipalsHoldNoAuthority` (Validate.s.sol:992) scans exactly six:
///          `[queueKeeper, frTreasury, feeRecipient, anchorCurator, attester1, attester2]`.
///        - `HandoverOps._assertNoSurvivingPrivilege` (Handover.s.sol:465) never consults the
///          governor at all.
///
///      WHY THE EXISTING SUITE MISSES IT. `SweepR2_PrincipalAxisBlindSpot.t.sol:72` sets
///      `c.proposalGuardian = attester2Addr` — aliasing the guardian onto a principal that IS
///      scanned. Give the guardian its own address and the hole opens. That aliasing is the only
///      difference between that fixture and this one.
///
///      CONSEQUENCE. A ceremony that grants the guardian multisig `UPGRADER_ROLE` on the sUSDfr
///      vault — by wiring, or by one mis-copied line — passes `Handover`'s no-surviving-privilege
///      assertion AND prints `VALIDATION PASSED` / `HANDOVER VALIDATION PASSED`. The guardian can
///      then call `vault.upgradeToAndCall(evil, ...)` with NO TIMELOCK in the path and take every
///      senior deposit, while holding a lifecycle veto over the proposals that would revoke it.
///
///      HOW TO READ THIS FILE — it is two-sided by construction:
///        - `test_P31_guardianHoldingVaultUpgraderIsRefusedByBothValidators` REDs on the accepted
///          tree and GREENs once the guardian is scanned. A discriminator that cannot go red proves
///          nothing.
///        - the two controls GREEN on BOTH trees, so the fix cannot be "make Validate revert more".
contract FixP31GuardianPrivilegeScanTest is Test, Deploy, HandoverOps {
    address internal attester1Addr = makeAddr("p31Attester1");
    address internal attester2Addr = makeAddr("p31Attester2");
    address internal ops = makeAddr("p31Ops");
    address internal treasury = makeAddr("p31Treasury");
    address internal fees = makeAddr("p31Fees");
    address internal keeper = makeAddr("p31Keeper");
    address internal anchor = makeAddr("p31AnchorCurator");
    /// @dev THE ONLY MATERIAL DIFFERENCE from `SweepR2_PrincipalAxisBlindSpot`: the guardian is its
    ///      own principal rather than an alias of `attester2`, which is what production wiring does.
    address internal guardian = makeAddr("p31ProposalGuardian");

    address internal currentTreasury;

    function _prodCtx() internal view returns (Ctx memory c) {
        c.deployer = address(this);
        c.opsAdmin = ops;
        c.proposalGuardian = guardian;
        c.queueKeeper = keeper;
        c.frTreasury = treasury;
        c.feeRecipient = fees;
        c.anchorCurator = anchor;
        c.attester1 = attester1Addr;
        c.attester2 = attester2Addr;
        c.keepOpsAdmin = false;
    }

    function _run(Ctx memory c) internal returns (D memory d) {
        currentTreasury = c.frTreasury;
        d = _deployAll(c);
        _wire(d, c);
        _seed(d, c);
        _handover(d, c);
    }

    /// @dev One extra grant injected while the deployer still holds DEFAULT_ADMIN — i.e. a wiring
    ///      line a mistaken or malicious deployment script could carry.
    function _runWithInjectedGrant(Ctx memory c, bytes32 role, address grantee) internal returns (D memory d) {
        currentTreasury = c.frTreasury;
        d = _deployAll(c);
        _wire(d, c);
        IAccessControl(d.vault).grantRole(role, grantee);
        _seed(d, c);
        _handover(d, c);
    }

    function _args(D memory d, Ctx memory c) internal pure returns (Validate.M memory a) {
        a.compliance = d.compliance;
        a.usdfr = d.usdfr;
        a.reserves = d.reserves;
        a.controller = d.controller;
        a.vault = d.vault;
        a.points = d.points;
        a.registry = d.registry;
        a.oracle = d.oracle;
        a.bridge = d.bridge;
        a.curator = d.curator;
        a.waterfall = d.waterfall;
        a.defaultManager = d.defaultManager;
        a.assessedImpairmentSource = d.assessedImpairmentSource;
        a.mtmExecutor = d.mtmExecutor;
        a.queue = d.queue;
        a.grove = d.grove;
        a.sGrove = d.sGrove;
        a.timelock = d.timelock;
        a.governor = d.governor;
        a.votesAggregator = d.votesAggregator;
        a.deployer = c.deployer;
        a.opsAdmin = c.opsAdmin;
        a.proposalGuardian = c.proposalGuardian;
        a.queueKeeper = c.queueKeeper;
        a.attester1 = c.attester1;
        a.attester2 = c.attester2;
        a.frTreasury = c.frTreasury;
        a.feeRecipient = c.feeRecipient;
        a.anchorCurator = c.anchorCurator;
        a.stable = d.stable;
        a.keepOpsAdmin = false; // PRODUCTION SHAPE — the strict branch
        a.attesterQuorumIndependent = true;
    }

    // ── control ──────────────────────────────────────────────────────────

    /// @notice PRECONDITION, green on both trees. With a DISTINCT guardian and no injected grant,
    ///         this exact stack validates in both entry points — so any revert below is
    ///         attributable to the grant and not to the guardian having its own address.
    function test_P31_control_cleanCeremonyWithADistinctGuardianValidates() public {
        Ctx memory c = _prodCtx();
        D memory d = _run(c);
        Validate v = new Validate();
        v.validateDeployment(_args(d, c));
        v.validateHandover(_args(d, c));
    }

    /// @notice CONTROL, green on both trees. The SAME grant on a SCANNED principal is caught, which
    ///         proves the harness, the injection and the expected revert string are all correct —
    ///         so a red below is a gap in the scanned SET, not a broken test.
    function test_P31_control_theSameGrantOnAScannedPrincipalIsCaught() public {
        Ctx memory c = _prodCtx();
        D memory d = _runWithInjectedGrant(c, Roles.UPGRADER_ROLE, anchor);
        Validate v = new Validate();
        vm.expectRevert(bytes("PRODUCTION SHAPE: a named genesis principal holds a module AUTHORITY role"));
        v.validateDeployment(_args(d, c));
        vm.expectRevert(bytes("PRODUCTION SHAPE: a named genesis principal holds a module AUTHORITY role"));
        v.validateHandover(_args(d, c));
    }

    // ── the discriminator ────────────────────────────────────────────────

    /// @notice THE FINDING. `UPGRADER_ROLE` on the sUSDfr vault is `_authorizeUpgrade` — total
    ///         authority over senior principal, with no timelock in the path. Held by the PROPOSAL
    ///         GUARDIAN it survives the entire production ceremony, because the handover only ever
    ///         acts on the two EOAs of record and the guardian is in neither validator's scanned
    ///         set. DETECTION is the whole remedy.
    ///
    ///         REDs on the accepted tree `279cad0`. GREENs once the guardian is scanned.
    function test_P31_guardianHoldingVaultUpgraderIsRefusedByBothValidators() public {
        Ctx memory c = _prodCtx();
        D memory d = _runWithInjectedGrant(c, Roles.UPGRADER_ROLE, guardian);

        assertTrue(
            IAccessControl(d.vault).hasRole(Roles.UPGRADER_ROLE, guardian),
            "precondition: the proposal guardian holds UPGRADER on the senior vault"
        );

        // The deployer receipt is clean, so nothing in the manifest hints at this.
        (address[] memory targets, string[] memory names) = PrivilegeAudit.moduleSet(_auditTargets(d));
        assertEq(
            PrivilegeAudit.scanEverything(targets, names, d.timelock, c.deployer).length,
            0,
            "the deployer receipt is clean, so the manifest gives no hint"
        );
        string[] memory guardianHeld = PrivilegeAudit.scanEverything(targets, names, d.timelock, guardian);
        for (uint256 i = 0; i < guardianHeld.length; ++i) {
            console2.log("P-31 proposalGuardian holds:", guardianHeld[i]);
        }
        assertEq(guardianHeld.length, 1, "precondition: exactly the injected pair");

        Validate v = new Validate();
        vm.expectRevert(bytes("PRODUCTION SHAPE: a named genesis principal holds a module AUTHORITY role"));
        v.validateDeployment(_args(d, c));
        vm.expectRevert(bytes("PRODUCTION SHAPE: a named genesis principal holds a module AUTHORITY role"));
        v.validateHandover(_args(d, c));
    }
}
