// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.30;

import {ClaimBridge} from "../../src/ClaimBridge.sol";
import {IAttestationOracle} from "../../src/interfaces/IAttestationOracle.sol";
import {Config} from "../../src/libraries/Config.sol";
import {RealOracleFixture} from "../helpers/RealOracleFixture.sol";

/// @title P-32 discriminator — the mint gate binds one payload out of three, so one deal's legal
///        paperwork authorises a different deal.
///
/// @dev WRITTEN BY THE AUDIT STREAM, NOT BY THE STREAM THAT WILL FIX IT. Same separation as the
///      cause-E/F, P-23 and P-31 discriminators. **Do not edit this file to match a fix.**
///
///      THE FINDING. `ClaimBridge._originate`'s gate loop asks only
///      `oracle.isSatisfied(nextId, kind)` — a PRESENCE BIT per kind. The payload binding
///      `_requireTermsAttested` is applied to `AttestationKind.CreditIssued` ALONE. So
///      `AssignmentExecuted` and `UCCFiled` are existence-only bits at a facility id, and facility
///      ids are strictly sequential (`nextId`) and therefore predictable. `attest` never consults
///      the bridge, so facts can be landed at ids that do not exist yet, and `attest` only requires
///      a non-zero payload for `Valuation`.
///
///      Note the fixture itself shows the shape of the problem: `_setSatisfied` attests with
///      `keccak256("fact", facilityId, kind, nonce)` — a payload committed to the **id**, saying
///      nothing about **which deal**.
///
///      WHAT THAT MEANS IN PRACTICE. Deal A — a small receivable from one obligor — is diligenced.
///      An attester lands `AssignmentExecuted` (the receivable is assigned to the SPV) and
///      `UCCFiled` (a financing statement perfects the lien) at the next facility id. Deal A then
///      falls through and is never originated; nothing clears or expires those facts. Deal B — a
///      different obligor, a different receivable, 30x the principal — is later underwritten, its
///      own `CreditIssued` quorum signs B's terms, and `originate(B)` succeeds at that same id
///      **against deal A's assignment and deal A's UCC financing statement**.
///
///      NO ATTACKER IS REQUIRED. Every step is a legitimate actor doing their job; a cancelled deal
///      plus a new deal is sufficient. Malice only makes it faster.
///
///      §1.3 says a Loan NFT cannot mint unless all required attestations are satisfied. They ARE
///      satisfied — but two of the three describe a different deal. The gate passes vacuously, and
///      `invariant_mintGate_neverBypassed` agrees, because it is not bypassed.
///
///      HOW TO READ THIS FILE — two-sided by construction:
///        - `test_P32_dealBCannotOriginateOnDealAsLegalPaperwork` REDs on the accepted tree and
///          GREENs once the gate binds all three attestations to the deal.
///        - the two controls GREEN on BOTH trees, so the fix cannot be "make origination revert
///          more" — a gate that refuses a properly attested deal is not a fix.
///
///      DELIBERATELY MECHANISM-AGNOSTIC. The discriminator asserts only that the origination FAILS.
///      It does not name an error, because the remedy is undecided — binding the payloads to a deal
///      identity, or binding the facts into one atomic group, would both satisfy it. Any correct fix
///      passes.
contract FixP32MintGateDealBindingTest is RealOracleFixture {
    uint256 internal constant DEAL_A_PRINCIPAL = 100_000e18;
    uint256 internal constant DEAL_B_PRINCIPAL = 3_000_000e18; // 30x, a different obligor
    bytes32 internal constant DEAL_A_REF = keccak256("deal-A-offchain-ref");
    bytes32 internal constant DEAL_B_REF = keccak256("deal-B-offchain-ref");

    function _terms(bytes32 borrowerId, uint256 principal, bytes32 offchainRef)
        internal
        view
        returns (ClaimBridge.OriginationTerms memory)
    {
        return _facilityTerms(
            Config.CLASS_FILM_TAX_CREDITS,
            borrowerId,
            STATE_GA,
            principal,
            FILM_LTV_BPS,
            FILM_RATE_BPS,
            uint64(block.timestamp + 365 days),
            offchainRef
        );
    }

    /// @dev The two LEGAL facts — the assignment and the UCC filing. These are what deal A's
    ///      diligence produces, and what deal B inherits.
    function _landLegalFacts(uint256 facilityId) internal {
        _setSatisfied(facilityId, IAttestationOracle.AttestationKind.AssignmentExecuted, true);
        _setSatisfied(facilityId, IAttestationOracle.AttestationKind.UCCFiled, true);
    }

    // ── controls: green on BOTH trees ────────────────────────────────────

    /// @notice PRECONDITION. A deal whose own three attestations are landed originates normally, so
    ///         a refusal below is attributable to the substitution and not to a broken gate.
    function test_P32_control_aFullyAttestedDealOriginates() public {
        uint256 nextId = bridge.totalOriginated() + 1;
        ClaimBridge.OriginationTerms memory termsB = _terms(BORROWER_2, DEAL_B_PRINCIPAL, DEAL_B_REF);

        _landLegalFacts(nextId);
        _attestCreditTerms(nextId, bridge.creditTermsHash(termsB));

        vm.prank(originator);
        bridge.originate(custodian, termsB);
    }

    /// @notice CONTROL. The gate does gate: without the legal facts, origination is refused. Proves
    ///         the harness and that `originate` is not simply permissive.
    function test_P32_control_aMissingLegalAttestationIsRefused() public {
        uint256 nextId = bridge.totalOriginated() + 1;
        ClaimBridge.OriginationTerms memory termsB = _terms(BORROWER_2, DEAL_B_PRINCIPAL, DEAL_B_REF);

        // Credit terms only — no assignment, no UCC.
        _attestCreditTerms(nextId, bridge.creditTermsHash(termsB));

        vm.prank(originator);
        (bool ok,) = address(bridge).call(abi.encodeCall(ClaimBridge.originate, (custodian, termsB)));
        assertFalse(ok, "origination succeeded with no assignment and no UCC filing");
    }

    // ── the discriminator ────────────────────────────────────────────────

    /// @notice THE FINDING. Deal A's assignment and UCC filing authorise deal B — a different
    ///         obligor, a different receivable, 30x the principal — at the same facility id.
    ///
    ///         REDs on the accepted tree `279cad0`. GREENs once all three attestations are bound to
    ///         the deal rather than merely present at the id.
    function test_P32_dealBCannotOriginateOnDealAsLegalPaperwork() public {
        uint256 nextId = bridge.totalOriginated() + 1;

        ClaimBridge.OriginationTerms memory termsA = _terms(BORROWER_1, DEAL_A_PRINCIPAL, DEAL_A_REF);
        ClaimBridge.OriginationTerms memory termsB = _terms(BORROWER_2, DEAL_B_PRINCIPAL, DEAL_B_REF);

        // ── deal A is diligenced: its legal facts and its credit terms land at `nextId` ──
        _landLegalFacts(nextId);
        _attestCreditTerms(nextId, bridge.creditTermsHash(termsA));

        // ── deal A falls through. It is NEVER originated, and nothing clears its facts. ──

        // ── deal B is underwritten later. Its own quorum signs B's terms at the SAME id. ──
        _attestCreditTerms(nextId, bridge.creditTermsHash(termsB));

        // Deal A's legal facts are still standing, untouched, and now describe deal B's facility.
        assertTrue(
            oracle.isSatisfied(nextId, IAttestationOracle.AttestationKind.AssignmentExecuted),
            "precondition: deal A's assignment is still satisfied at this id"
        );
        assertTrue(
            oracle.isSatisfied(nextId, IAttestationOracle.AttestationKind.UCCFiled),
            "precondition: deal A's UCC filing is still satisfied at this id"
        );

        vm.prank(originator);
        (bool ok,) = address(bridge).call(abi.encodeCall(ClaimBridge.originate, (custodian, termsB)));

        assertFalse(ok, "deal B originated against deal A's assignment and deal A's UCC financing statement");
    }
}
