// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.30;

// GENERATED by tools/generate-privilege-topology.mjs from config/privilege-topology.json.
// Do not edit this file directly; the compiler-AST topology gate rejects drift.

/// @title Roles
/// @notice Canonical role identifiers for the protocol's access-control matrix.
/// @dev DEFAULT_ADMIN_ROLE is inherited from AccessControl and represented by bytes32(0).
library Roles {
    // NOTE: A QUEUE_ROLE existed through Phase H but was never consumed. The vault gates its exit by the configured redemption-queue address, which is the stronger check; it was removed at Phase I cleanup.

    /// @notice May authorize UUPS upgrades. Held only by the governance timelock.
    bytes32 internal constant UPGRADER_ROLE = keccak256("UPGRADER_ROLE");

    /// @notice Emergency pause/unpause on value-moving paths. Cannot upgrade or move value.
    bytes32 internal constant GUARDIAN_ROLE = keccak256("GUARDIAN_ROLE");

    /// @notice May mint USDfr. Held only by the MintRedeemController.
    bytes32 internal constant MINTER_ROLE = keccak256("MINTER_ROLE");

    /// @notice Reserve custody operations (deposit/release). Held only by the MintRedeemController.
    bytes32 internal constant CONTROLLER_ROLE = keccak256("CONTROLLER_ROLE");

    /// @notice Principal deployment, atomic payment receipt, and writedown. Held by credit modules.
    bytes32 internal constant CREDIT_ROLE = keccak256("CREDIT_ROLE");

    /// @notice May burn USDfr to realize an authenticated loss. Held only by DefaultManager and ReserveManager.
    /// @dev AUDIT R16-M1: burnLoss is deliberately split from CREDIT_ROLE so the repayment engine cannot compose mint and burn authority.
    bytes32 internal constant LOSS_BURNER_ROLE = keccak256("LOSS_BURNER_ROLE");

    /// @notice May bracket a junior-capacity change so the vault preserves its asset-denominated performance-fee hurdle. Held only by the curator, sGROVE, and DefaultManager modules.
    bytes32 internal constant FEE_ACCOUNTING_ROLE = keccak256("FEE_ACCOUNTING_ROLE");

    /// @notice Manages KYC allowlist and jurisdiction blocklist entries.
    bytes32 internal constant COMPLIANCE_ADMIN_ROLE = keccak256("COMPLIANCE_ADMIN_ROLE");

    /// @notice Reserve configuration and conservative USDC custody write-downs.
    bytes32 internal constant RESERVE_ADMIN_ROLE = keccak256("RESERVE_ADMIN_ROLE");

    /// @notice May originate facilities (Phase D).
    bytes32 internal constant ORIGINATOR_ROLE = keccak256("ORIGINATOR_ROLE");

    /// @notice Authorized attesters (Phase G, ADR-0007).
    bytes32 internal constant ATTESTER_ROLE = keccak256("ATTESTER_ROLE");

    /// @notice Servicing operations: facility funding, repayment distribution, default declaration, and loss realization. Held by Forest Road servicing keys until Phase G binds these paths to attested facts; the role then gates who may execute an already-attested action, not what is true.
    bytes32 internal constant SERVICER_ROLE = keccak256("SERVICER_ROLE");

    /// @notice Drives RedemptionQueue.closeEpoch. Operational, not governance or upgrade authority: it initiates a financially effective settlement and controls when its budget is sampled, but cannot choose recipients, reorder FIFO, set parameters, or exceed the contract-enforced budget and pricing rules.
    /// @dev AUDIT FIX D7-01: closeEpoch samples the epoch liquidity budget as a spot read and the fill loop re-reads it every chunk. While permissionless, a caller could hold flash liquidity across both reads; measured excess budget was $1.62M from Morpho alone and $4.31M from stacked Aave and Morpho borrowing. A flash loan cannot span two transactions, so the keeper gate closes the vector at its root. This supersedes ADR-0018 section 2's permissionless-settlement design. Grant the role to at least two holders: a hot keeper and a manual ops-multisig backstop. A total keeper outage is bounded only by governance regranting the role. A permissionless grace fallback was rejected because it would restore the flash vector whenever the keeper missed the window.
    bytes32 internal constant SETTLEMENT_KEEPER_ROLE = keccak256("SETTLEMENT_KEEPER_ROLE");
}
